# Claude Session Manager Default Configuration
# This file contains default settings that can be overridden by:
# 1. User config file at ~/.config/claude-session-manager/config.yaml
# 2. Environment variables with CSM_ prefix
# 3. Command line flags

# HTTP Server Configuration
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 15      # seconds
  write_timeout: 15     # seconds
  shutdown_timeout: 10  # seconds
  
  # CORS Configuration
  cors:
    enabled: true
    allowed_origins:
      - "*"
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed_headers:
      - Origin
      - Content-Type
      - Accept
      - Authorization
    allow_credentials: true
    max_age: 86400  # 24 hours

# Claude Configuration
claude:
  # Base directory for Claude data (defaults to ~/.claude)
  # home_directory: ~/.claude
  
  # Projects directory path (defaults to ~/.claude/projects)
  # projects_path: ~/.claude/projects
  
  # File system watch interval in seconds
  watch_interval: 5
  
  # Cache refresh rate in minutes (backup to file watcher)
  cache_refresh_rate: 5

# Token Pricing Configuration
pricing:
  # Cost per 1,000 input tokens
  input_tokens_per_k: 0.01
  
  # Cost per 1,000 output tokens
  output_tokens_per_k: 0.03
  
  # Currency for cost calculations
  currency: USD

# Feature Flags and Settings
features:
  # Enable WebSocket support for real-time updates
  enable_websocket: true
  
  # Enable file system watcher for session changes
  enable_file_watcher: true
  
  # Enable metrics collection
  enable_metrics: false
  
  # Enable profiling endpoints
  enable_profiling: false
  
  # Enable debug mode
  debug_mode: false